Core_clientes/Core_clientes/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core_clientes.Models;
using System.Security.Policy;

namespace Core_clientes.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }
        public DbSet<Cliente> Cliente { get; set; }
    }
}

Core_clientes/Core_clientes/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Core_clientes.Models
{
    public class Cliente
    {
            [Key]
            public int Cliid { get; set; }

            [Required(ErrorMessage = "Enter the client name")]
            [Display(Name = "Client Name")]
            public string Cliname { get; set; }

            [Required(ErrorMessage = "Enter the client email")]
            [Display(Name = "Email")]
            [EmailAddress(ErrorMessage = "Enter a valid email address")]
            public string Email { get; set; }

            [Required(ErrorMessage = "Enter the client credit")]
            [Display(Name = "Credit")]
            [Range(0, 1000000)]
            public int Credit { get; set; }

            [Required(ErrorMessage = "Enter the client age")]
            [Display(Name = "Age")]
            [Range(20, 50)]
            public int Age { get; set; }
        }

}

Core_clientes/Core_clientes/Models/ErrorViewModel.cs
using System;

namespace Core_clientes.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Core_clientes/Core_clientes/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Core_clientes.Models;
using System.Security.Cryptography.X509Certificates;
using Microsoft.EntityFrameworkCore;

namespace Core_clientes.Controllers
{
    public class ClienteController : Controller
    {
        /*Varibale para accder a base de datos*/
        private readonly ApplicationDbContext _db;

        /*Constructor*/
        public ClienteController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var displaydata = _db.Cliente.ToList();
            return View(displaydata);
        }

        [HttpGet]
        public async Task<IActionResult> Index(string CliSearch)
        {
            ViewData["GetClienteDetail"] = CliSearch; 
             var Cliquery = from x in _db.Cliente select x;
            if (!String.IsNullOrEmpty(CliSearch))
            {
                Cliquery = Cliquery.Where(x => x.Cliname.Contains(CliSearch) ||
                x.Email.Contains(CliSearch));
            }
            return View(await Cliquery.AsNoTracking().ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Cliente nCli)
        {
            if (ModelState.IsValid)
            {
                _db.Add(nCli);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(nCli);
        }

        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getCliDetail = await _db.Cliente.FindAsync(id);
            return View(getCliDetail);
        }


        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getCliDetail = await _db.Cliente.FindAsync(id);
            return View(getCliDetail);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Cliente oldCli)
        {
            if (ModelState.IsValid)
            {
                _db.Update(oldCli);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(oldCli);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) 
            {
                return RedirectToAction("Index");
            }
            var getCliDetail = await _db.Cliente.FindAsync(id);
            return View(getCliDetail);
        }
       
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var getCliDetail = await _db.Cliente.FindAsync(id);
            _db.Cliente.Remove(getCliDetail);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    }
}

Core_clientes/Core_clientes/Views/Cliente/Create.cshtml
@model Core_clientes.Models.Cliente

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cliname" class="control-label"></label>
                <input asp-for="Cliname" class="form-control" />
                <span asp-validation-for="Cliname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Credit" class="control-label"></label>
                <input asp-for="Credit" class="form-control" />
                <span asp-validation-for="Credit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Core_clientes/Core_clientes/Views/Cliente/Delete.cshtml
@model Core_clientes.Models.Cliente

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Estas seguro que quieres eliminar el cliente?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Credit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Credit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Core_clientes/Core_clientes/Views/Cliente/Detail.cshtml
@model Core_clientes.Models.Cliente

@{
    ViewData["Title"] = "Detail";
}

<h1>Detail</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Credit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Credit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Cliid }) |
    <a asp-action="Index">Back to List</a>
</div>

Core_clientes/Core_clientes/Views/Cliente/Edit.cshtml
@model Core_clientes.Models.Cliente

@{
    ViewData["Title"] = "Edit";
}

<h1>Actualizar datos</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cliid" class="control-label"></label>
                <input asp-for="Cliid" class="form-control" readonly />
                <span asp-validation-for="Cliid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cliname" class="control-label"></label>
                <input asp-for="Cliname" class="form-control" />
                <span asp-validation-for="Cliname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Credit" class="control-label"></label>
                <input asp-for="Credit" class="form-control" />
                <span asp-validation-for="Credit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Core_clientes/Core_clientes/Views/Cliente/Index.cshtml
@model IEnumerable<Core_clientes.Models.Cliente>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-action="Index" method="get">
    <p>
        <i class=" fa fa-search"></i>
        <input type="search" placeholder=" Ingresa Nombre o Email..." name="CliSearch"
               value="@ViewData["GetClienteDetail"]" style="width:500px;" />
        <input type="submit" value="Buscar" class="btn btn-primary" />
        <a asp-action="Index">Ver todos</a>
    </p>
</form>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Cliid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cliname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Credit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Cliid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cliname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Credit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id=item.Cliid }, new { @class = "btn betn-primary"}) |
                @Html.ActionLink("Detalles", "Detail", new { id = item.Cliid }, new { @class = "btn btn-success"}) |
                @Html.ActionLink("Eliminar", "Delete", new { id = item.Cliid },new { @class="btn btn-danger"})
            </td>
        </tr>
}
    </tbody>
</table>

Core_clientes/Core_clientes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Core_clientes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Cliente" asp-action="Index">Core_clientes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Core_clientes - <a asp-area="" asp-controller="Clientes" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>